### ISSUE TITLE
Suggestion: Change color to something clearer

### ISSUE THREAD

**Issue by skacuweb1** [skaculate/firstska#1]
I believe for people who spend more time on the screen, blue should be something that works well for them. And also, it also follows the color rules well!

```CSS
h1 {
  color: #0cb3fa;
}

a {
  color: #08db95;
}

```
